Repository sodadata/soda-core, pull requests merged in 2022-06, with the labels that each got.

#1390 feat: send outcome reason to cloud for anomaly detection and schema checks
  soda/core/soda/execution/anomaly_metric_check.py
  soda/core/soda/execution/check.py
  soda/core/soda/execution/schema_check.py
  soda/core/soda/soda_cloud/soda_cloud.py
  soda/core/tests/data_source/test_anomaly_check.py
  soda/core/tests/data_source/test_schema_changes.py
  soda/core/tests/helpers/mock_soda_cloud.py
  soda/scientific/soda/scientific/anomaly_detection/anomaly_detector.py
  soda/scientific/soda/scientific/anomaly_detection/models/prophet_model.py
Labels: enhancement

#1444 Change: rename the `update` command to `update-dro` as it better describes what the command is used for
  soda/core/soda/cli/cli.py
  soda/core/tests/cli/test_cli_update_distribution_file.py
  soda/core/tests/data_source/test_distribution_check.py
  soda/scientific/soda/scientific/distribution/comparison.py
Labels: breaking-change

#1447 feat/fix: ensure empty bins for integer columns are not created and fix bin width derivation
  soda/core/soda/execution/data_source.py
  soda/core/soda/execution/profile_columns_run.py
Labels: enhancement

#1449 Do not quote table names in for-each block
  soda/core/soda/scan.py
Labels: bug

#1442 feat: add env based option to run tests on views
  .env.example
  soda/bigquery/tests/bigquery_data_source_fixture.py
  soda/core/tests/data_source/test_discover_tables.py
  soda/core/tests/helpers/common_test_tables.py
  soda/core/tests/helpers/data_source_fixture.py
  soda/core/tests/helpers/test_table.py
  soda/redshift/soda/data_sources/redshift_data_source.py
Labels: enhancement

#1457 Re-add telemetry data source attributes
  soda/core/soda/execution/data_source.py
  soda/core/soda/execution/data_source_manager.py
Labels: bug

#1464 feat: Add `samples limit` to failed rows checks
  soda/core/soda/execution/query.py
  soda/core/soda/execution/user_defined_failed_rows_expression_check.py
  soda/core/soda/execution/user_defined_failed_rows_expression_query.py
  soda/core/soda/execution/user_defined_failed_rows_metric.py
  soda/core/soda/execution/user_defined_failed_rows_query.py
  soda/core/soda/sampler/sample_context.py
  soda/core/soda/sampler/soda_cloud_sampler.py
  soda/core/soda/scan.py
  soda/core/soda/soda_cloud/soda_cloud.py
  soda/core/soda/sodacl/sodacl_parser.py
  soda/core/soda/sodacl/user_defined_failed_rows_check_cfg.py
  soda/core/soda/sodacl/user_defined_failed_rows_expression_check_cfg.py
  soda/core/tests/data_source/test_user_defined_failed_rows_checks.py
Labels: enhancement
