Repository sodadata/soda-core, pull requests merged in 2023-03, with the labels that each got.

#1833 fix: seasonality feedback overwrites skip measurements feedback
  soda/scientific/soda/scientific/anomaly_detection/detector_config.yaml
  soda/scientific/tests/anomaly_detection/anomaly_detector_test.py
  soda/scientific/tests/assets/anomaly_detection_assets.py
Labels: ia-criticality:medium

#1841 Fix wrong parsing of scheme for soda_cloud
  soda/core/soda/configuration/configuration_parser.py
  soda/core/tests/unit/test_configuration_yaml_parser.py
Labels: bug

#1850 fix: improve error handling when invalid metric is provided to AnomalyMetricCheck
  soda/core/soda/execution/check/anomaly_metric_check.py
  soda/core/tests/data_source/test_anomaly_check.py
Labels: ia-criticality:low

#1847 feat: derive bins and weights for categorical DRO in SQL warehouse
  soda/core/soda/cli/cli.py
  soda/core/soda/execution/check/distribution_check.py
  soda/core/tests/cli/test_cli_update_distribution_file.py
  soda/core/tests/helpers/common_test_tables.py
  soda/scientific/soda/scientific/distribution/generate_dro.py
  soda/scientific/tests/generate_dro_test.py
Labels: ia-criticality:high
