Repository sodadata/soda-core, pull requests merged in 2023-02, with the labels that each got.

#1775 refactor: profiler implementation
  soda/core/soda/execution/check/profile_columns_run.py
  soda/core/soda/execution/data_source.py
  soda/core/soda/profiling/numeric_column_profiler.py
  soda/core/soda/profiling/profile_columns_result.py
  soda/core/soda/profiling/text_column_profiler.py
  soda/core/tests/data_source/test_profile_columns.py
  soda/dask/soda/data_sources/dask_data_source.py
Labels: refactoring, profiling, ia-criticality:high

#1780 fix: confidence bounds of anomaly detection sit too close together
  soda/core/soda/execution/check/anomaly_metric_check.py
  soda/core/tests/data_source/test_profile_columns.py
  soda/scientific/soda/scientific/anomaly_detection/anomaly_detector.py
  soda/scientific/soda/scientific/anomaly_detection/models/prophet_model.py
  soda/scientific/tests/anomaly_detection/anomaly_detector_test.py
Labels: ia-criticality:high

#1787 bug: anomaly detection doesn't use more than 3 historical check results
  soda/core/soda/execution/check/anomaly_metric_check.py
  soda/core/tests/data_source/test_anomaly_check.py
Labels: anomaly-detection, ia-criticality:low

#1808 refactor: only use last `n_points` in `detect_anomalies` method
  soda/scientific/soda/scientific/anomaly_detection/models/prophet_model.py
Labels: ia-criticality:low

#1799 fix: skip/ignore measurements does not work
  soda/scientific/soda/scientific/anomaly_detection/models/base.py
  soda/scientific/tests/anomaly_detection/anomaly_detector_test.py
Labels: ia-criticality:medium

#1797 bug: fix anomaly result to expect feedback outside of anomaly diagnostics
  soda/scientific/soda/scientific/anomaly_detection/anomaly_detector.py
  soda/scientific/soda/scientific/anomaly_detection/models/prophet_model.py
Labels: ia-criticality:low
